from sense_hat import SenseHat
from time import sleep


while True:
    sense = SenseHat()
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/dino.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/dog.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/gummy.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/flow.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/lady.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/tea.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/snake.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/wolf.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/hi.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/vader.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/tree.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/house2.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/cactus.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/llm.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/vader2.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/dog2.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/walk.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/excm.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/ship.png")
    sleep(1)
    sense.load_image("/home/galaxy/TedsWork/CODING/SenseHat/pix/flow2.png")
    sleep(1)